name: push-workflow
on: push

jobs:
    push-job:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: echo hello world et
        - name: step2
          run: |
            echo hello world
            echo github action
            
